opencloud:
    tenant:
        datasource:
            driver-class-name: com.mysql.jdbc.Driver
            password: root
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:mysql://localhost:3306/open-platform?useSSL=false&useUnicode=true&characterEncoding=utf-8
            username: root
        tenantId: tenant1234
server:
    port: 6878
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/open-platform?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
