management:
    endpoints:
        web:
            exposure:
                include: refresh,health
opencloud:
    swagger2:
        description: \u8FD0\u8425\u540E\u53F0\u670D\u52A1
        enabled: true
        title: \u8FD0\u8425\u540E\u53F0\u670D\u52A1
