hystrix:
  command:
    default:
      execution:
        isolation:
          semaphore:
            max-semaphores: 1000
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: true
  threadpool:
    default:
      coreSize: 1000.0
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,refresh-gateway
opencloud:
  #网关配置
  api-gateway:
    #动态权限控制
    access-control: true
    #校验参数签名
    check-sign: false
    #无需鉴权准入
    not-authority-allow: /auth/user/me,/base/authority/granted/me,/base/authority/granted/me/menu
    #始终方向
    permit-all: /login/**,/logout,/oauth/*,/auth/login/**,/auth/logout,/auth/oauth/**,/admin/login/token
  #\u7F51\u5173\u8DE8\u57DF\u914D\u7F6E
  cors:
    allow-credentials: true
    allowed-header: '*'
    allowed-method: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-origin: '*'
    enabled: true
    max-age: 86400
  swagger2:
    description: \u83B7\u53D6\u5F53\u524D\u767B\u5F55\u7528\u6237:OpenHelper.getUser()<br>\u63A5\u53E3\u8C03\u7528\u5730\u5740:${opencloud.common.api-server-addr}<br>SSO\u5355\u70B9\u767B\u51FA\u5730\u5740:${opencloud.common.api-server-addr}/logout<br>SSO\u5355\u70B9\u767B\u5F55\u9875\u5730\u5740:${opencloud.common.user-authorization-uri}<br>Oauth2\u83B7\u53D6token\u5730\u5740:${opencloud.common.access-token-uri}<br>Oauth2\u6821\u9A8Ctoken\u5730\u5740:${opencloud.common.token-info-uri}<br>\u5F00\u542F\u53C2\u6570\u9A8C\u7B7E:${opencloud.api-gateway.check-sign}<br>\u5F00\u542F\u52A8\u6001\u8BBF\u95EE\u63A7\u5236:${opencloud.api-gateway.access-control}<br>\u5237\u65B0\u7F51\u5173\u76D1\u63A7\u7AEF\u70B9(\u667A\u80FD\u8DEF\u7531\u3001\u9650\u6D41\u7B56\u7565\u3001IP\u8BBF\u95EE\u7B56\u7565\u3001\u6743\u9650):http://${opencloud.common.api-server-addr}/actuator/refresh-gateway?destination=opencloud-gateway-provider:*
    enabled: true
    title: 开放API服务
ribbon:
  ConnectTimeout: 30000
  MaxAutoRetries: 10
  MaxAutoRetriesNextServer: 10
  MaxConnectionsPerHost: 100
  MaxTotalHttpConnections: 1000
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000
zuul:
  add-host-header: true
  host:
    connect-timeout-millis: 10000
    max-per-route-connections: 500
    max-total-connections: 1000
    socket-timeout-millis: 60000
  ignored-services: '*'
  ratelimit:
    behind-proxy: true
    enabled: true
    key-prefix: cloud_rate_limit
    repository: REDIS
  routes:
    opencloud-admin-provider:
      path: /admin/**
      serviceId: com.opencloud.admin.provider
    opencloud-auth-provider:
      path: /auth/**
      serviceId: com.opencloud.auth.provider
    opencloud-base-provider:
      path: /base/**
      serviceId: com.opencloud.base.provider
    opencloud-msg-provider:
      path: /msg/**
      serviceId: com.opencloud.msg.provider
    opencloud-scheduler-provider:
      path: /scheduler/**
      serviceId: com.opencloud.task.provider
  semaphore:
    max-semaphores: 1000
  sensitive-headers: ''
