management:
    endpoints:
        web:
            exposure:
                include: refresh,health
opencloud:
    sms:
        aliyun:
            accessKeyId: xxxxx
            accessKeySecret: xxxxx
        type: aliyun
    swagger2:
        description: \u5E73\u53F0\u6D88\u606F\u670D\u52A1
        enabled: true
        title: \u5E73\u53F0\u6D88\u606F\u670D\u52A1
spring:
    mail:
        host: smtp.qq.com
        password: xxuodpomaosmbjaj
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
        username: 515608851@qq.com
