management:
    endpoints:
        web:
            exposure:
                include: refresh,health
opencloud:
    sms:
        aliyun:
            accessKeyId: xxxxx
            accessKeySecret: xxxxx
        type: aliyun
    swagger2:
        description: 平台消息服务
        enabled: true
        title: 平台消息服务
spring:
    mail:
        host: smtp.qq.com
        password: xxuodpomaosmbjaj
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
        username: 515608851@qq.com
