management:
    endpoints:
        web:
            exposure:
                include: refresh,health
opencloud:
    swagger2:
        description: APP认证服务Demo
        enabled: true
        title: APP认证服务Demo
spring:
    mvc:
        throw-exception-if-no-handler-found: true
    redis:
        database: 1
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: LEGACYHTML5
        prefix: classpath:/templates/
        suffix: .html
